import PatientTabBar from '@/components/PatientTabBar'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Prescribe best medicine to your patients',
  description: 'Generated by create next app',
}

export default function PatientLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section className='py-3 container'>
      <PatientTabBar/>
      {children}
    </section>
  )
}
